check_tables:
  courses: tbleFDCQBG74x5sp
  lessons: tbl04aHyg3FzM5sQ
processed_videos:
- jNQXAC9IVRw
- DQacCB9tDaw
- dQw4w9WgXcQ
- M7lc1UVf-VE
- kAm7iQygImo
- YE0zPzmUnXc
- nvbq39yVYRk
- 5KTHvKCrQ00
- uBJdwRPO1QE
- yGJORJdej_s
- hbfrZriq0f8
- J9982NLmTXg
- 6qAB6aUMIeA
- z1ISq9Ty4Cg
- 741j2Jne1EM
- AbmQFGTyJKA
- ChDw2Vd_bBE
- Vut9hUEKyfk
- CHd5hajpmxI
- XWi8HMxU99k
- kcEQlp_QGJo
- VQXivhM8I-g
- TqAgejIX7uU
- BHlko_Mg-Jk
- AmdLVWMdjOk
- 836CauoVekQ
- TOsNrV3bXtQ
- WHWAYiY_RnQ
- 0YaJQZZACy8
- it_2BPnAI8I
- Za3Zk7LqQhk
- 7TyCmd78qJU
- ZkXrTHpnQrQ
- 3zdc_luRgWA
- 6ZimKgm4sxw
- 1IcfJBdxzWk
- 4suX93GcjCo
- TBRcvGqV6xk
- zQUO39j_c_k
- UPW3iSLPrPg
- lkbr5qnYSUU
- JYqAWNVHBwo
